spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 配置文件的真实位置
  messages:
    basename: i18n.login

#整合mybatis
mybatis:
  type-aliases-package: com.clp.pojo
  mapper-locations: classpath:mapper/*.xml

#分页
pagehelper:
  helper-dialect: mysql
  #分页参数合理化（当前页不会小于1或者大于最大页）
  reasonable: true

